#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Dec 30, 2019 03:31:08 PM PST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global inputVAR
    inputVAR = tk.StringVar()

def gimmeInches():
    _in = float(inputVAR.get())
    _out = round(_in / 25.4, 5)
    inputVAR.set(_out)
    widget = root.focus_get()
    widget.selection_range(0, 'end')
    root.clipboard_clear()
    root.clipboard_append(_out)


    sys.stdout.flush()

def enter(event):
    gimmeInches()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import ConvertMM
    ConvertMM.vp_start_gui()




